version = 1

[[migrations]]
id = 8902977264178818865
name = "0000_init.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 2785198260885618881
name = "0001_add_people.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
id = 5131349434528572395
name = "0002_add_statements.sql"
snapshot_name = "0002_snapshot.toml"

[[migrations]]
id = 1804448011042176275
name = "0003_add_assignment_guesses.sql"
snapshot_name = "0003_snapshot.toml"

[[migrations]]
id = 4965747564171861539
name = "0004_add_purchased_on_index.sql"
snapshot_name = "0004_snapshot.toml"

[[migrations]]
id = 6665813495237729523
name = "0005_add_refund_links.sql"
snapshot_name = "0005_snapshot.toml"
